import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1758663881290 implements MigrationInterface {
    name = 'InitialSchema1758663881290'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "departamento" ("id" SERIAL NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "carreraId" integer, CONSTRAINT "UQ_574b538a96151008aa904a8d6f6" UNIQUE ("nombre"), CONSTRAINT "PK_7fd6f336280fd0c7a9318464723" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carrera" ("id" SERIAL NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_03d7578c3da1bf8dcf11a0c26a5" UNIQUE ("nombre"), CONSTRAINT "PK_0fd6015695e5bf3f8a7f9e27711" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plan_estudio" ("id" SERIAL NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "añoInicio" integer, "añoFin" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "carreraId" integer, CONSTRAINT "PK_1b3b1a37cebc59d03dc22547a7b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."evaluaciones_tipo_enum" AS ENUM('parcial', 'trabajo_practico', 'laboratorio', 'participacion', 'recuperatorio')`);
        await queryRunner.query(`CREATE TYPE "public"."evaluaciones_estado_enum" AS ENUM('aprobada', 'desaprobada', 'ausente', 'pendiente')`);
        await queryRunner.query(`CREATE TABLE "evaluaciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo" "public"."evaluaciones_tipo_enum" NOT NULL, "titulo" character varying, "nota" integer, "estado" "public"."evaluaciones_estado_enum" NOT NULL DEFAULT 'pendiente', "fecha" TIMESTAMP NOT NULL DEFAULT now(), "observaciones" character varying, "inscripcionId" integer, "materiaId" integer, "estudianteId" integer, "cargadoPorId" integer, CONSTRAINT "PK_3b157bcce651495e675cdf96a14" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."asistencia_estado_enum" AS ENUM('presente', 'ausente', 'justificada')`);
        await queryRunner.query(`CREATE TABLE "asistencia" ("id" SERIAL NOT NULL, "estado" "public"."asistencia_estado_enum" NOT NULL DEFAULT 'ausente', "motivoJustificacion" character varying, "fechaRegistro" TIMESTAMP NOT NULL DEFAULT now(), "claseId" integer, "estudianteId" integer, CONSTRAINT "PK_2402857e8fb33d6c0fe23724b54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."clase_estado_enum" AS ENUM('programada', 'realizada', 'cancelada')`);
        await queryRunner.query(`CREATE TABLE "clase" ("id" SERIAL NOT NULL, "fecha" TIMESTAMP NOT NULL, "estado" "public"."clase_estado_enum" NOT NULL DEFAULT 'programada', "motivoCancelacion" character varying, "materiaId" integer, "horarioId" integer, "comisionId" integer, "docenteId" integer, CONSTRAINT "PK_9a493a2bbf7d40e3738abcedc31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comision" ("id" SERIAL NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "materiaId" integer, "profesorId" integer, CONSTRAINT "PK_b131d9949148c5aa6d80795652a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."horario_dia_enum" AS ENUM('domingo', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado')`);
        await queryRunner.query(`CREATE TABLE "horario" ("id" SERIAL NOT NULL, "dia" "public"."horario_dia_enum" NOT NULL, "horaInicio" TIME NOT NULL, "horaFin" TIME NOT NULL, "aula" character varying NOT NULL, "materiaId" integer, "docenteId" integer, "comisionId" integer, CONSTRAINT "PK_3c89ff4250bf835ce1f861313c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inscripcion_examen" ("id" SERIAL NOT NULL, "estado" character varying NOT NULL DEFAULT 'inscripto', "nota" integer, "fechaInscripcion" TIMESTAMP NOT NULL DEFAULT now(), "inscripcionId" integer, "examenId" integer, CONSTRAINT "PK_0444d4374e52286c08e1e04125f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "examen_final" ("id" SERIAL NOT NULL, "nota" integer, "estado" character varying NOT NULL DEFAULT 'inscripto', "materiaId" integer, "estudianteId" integer, CONSTRAINT "PK_0dbc68a86d4c78d23bf1599857a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "correlativas_cursada" ("id" SERIAL NOT NULL, "materiaId" integer, "correlativaId" integer, CONSTRAINT "PK_53511be1b4401dc0e8b580e7855" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "correlativas_final" ("id" SERIAL NOT NULL, "materiaId" integer, "correlativaId" integer, CONSTRAINT "PK_dad99dbd67603cce28f5cf6cd68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "materia" ("id" SERIAL NOT NULL, "nombre" character varying NOT NULL, "descripcion" character varying, "departamentoId" integer, "jefeCatedraId" integer, CONSTRAINT "REL_6fe2237e9ca17e0a1565ddd1c5" UNIQUE ("jefeCatedraId"), CONSTRAINT "PK_a8b21a045c6a7d9cfffc3a2ab26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inscripcion" ("id" SERIAL NOT NULL, "faltas" integer NOT NULL DEFAULT '0', "notaFinal" integer, "stc" character varying, "fechaInscripcion" TIMESTAMP NOT NULL DEFAULT now(), "fechaFinalizacion" TIMESTAMP NOT NULL DEFAULT now(), "estudianteId" integer, "materiaId" integer, "comisionId" integer, "planEstudioId" integer, CONSTRAINT "PK_bdff6201e066cec231d770912bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_rol_enum" AS ENUM('admin', 'estudiante', 'profesor', 'secretaria_academica')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "nombre" character varying NOT NULL, "apellido" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "legajo" character varying NOT NULL, "dni" character varying NOT NULL, "rol" "public"."user_rol_enum" NOT NULL DEFAULT 'estudiante', "planEstudioId" integer, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."estado_academico_estado_enum" AS ENUM('no_cursada', 'cursando', 'regular', 'aprobada', 'libre')`);
        await queryRunner.query(`CREATE TABLE "estado_academico" ("id" SERIAL NOT NULL, "estado" "public"."estado_academico_estado_enum" NOT NULL DEFAULT 'no_cursada', "notaCursada" integer, "notaFinal" integer, "fechaAprobacion" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "estudianteId" integer, "materiaId" integer, CONSTRAINT "PK_8931bea53734eef9d5760f5c4a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "materia_planes_estudio" ("planEstudioId" integer NOT NULL, "materiaId" integer NOT NULL, CONSTRAINT "PK_2463d09ec5dd633f4c8ab072da9" PRIMARY KEY ("planEstudioId", "materiaId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c855ceccd6a1bafda47c5d986d" ON "materia_planes_estudio" ("planEstudioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_89119a766cc38d3b471c44f1c5" ON "materia_planes_estudio" ("materiaId") `);
        await queryRunner.query(`CREATE TABLE "materia_profesores" ("materiaId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_8007b008a41f1892a2b56043472" PRIMARY KEY ("materiaId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d843d814b3b533333e65490d02" ON "materia_profesores" ("materiaId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6861a3382a55c8a497e59bfa02" ON "materia_profesores" ("userId") `);
        await queryRunner.query(`ALTER TABLE "departamento" ADD CONSTRAINT "FK_2fd9711a13a99100621e6122741" FOREIGN KEY ("carreraId") REFERENCES "carrera"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plan_estudio" ADD CONSTRAINT "FK_18a90835b62888c63219633bca3" FOREIGN KEY ("carreraId") REFERENCES "carrera"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluaciones" ADD CONSTRAINT "FK_794c93fa7feaf1bdda025827c48" FOREIGN KEY ("inscripcionId") REFERENCES "inscripcion"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluaciones" ADD CONSTRAINT "FK_1afd8efb246281fe06e9e1bc65b" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluaciones" ADD CONSTRAINT "FK_26177eb590949744dfd2d625ac4" FOREIGN KEY ("estudianteId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluaciones" ADD CONSTRAINT "FK_5819c9fc55bb56964c775d40d31" FOREIGN KEY ("cargadoPorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asistencia" ADD CONSTRAINT "FK_197feedf6c94e57846e6b436a4e" FOREIGN KEY ("claseId") REFERENCES "clase"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asistencia" ADD CONSTRAINT "FK_dc055a54b200f09315ee60a8e22" FOREIGN KEY ("estudianteId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clase" ADD CONSTRAINT "FK_03880ab206e6c9173496407b186" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clase" ADD CONSTRAINT "FK_df1e638ab6203b480e17ae6011d" FOREIGN KEY ("horarioId") REFERENCES "horario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clase" ADD CONSTRAINT "FK_fb7f4acc691e9f579f39225fcfe" FOREIGN KEY ("comisionId") REFERENCES "comision"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clase" ADD CONSTRAINT "FK_8cd6d132d0278db578b370e6bd7" FOREIGN KEY ("docenteId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comision" ADD CONSTRAINT "FK_3b031ff32fb1f21b9eec28e20e2" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comision" ADD CONSTRAINT "FK_3eec2023337a05b05082e615e3c" FOREIGN KEY ("profesorId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "horario" ADD CONSTRAINT "FK_2c31906f1be137431292d0766e9" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "horario" ADD CONSTRAINT "FK_7c707c9c1f8b56b381e12162c2f" FOREIGN KEY ("docenteId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "horario" ADD CONSTRAINT "FK_e15f4d22e3e790a903e5eef565a" FOREIGN KEY ("comisionId") REFERENCES "comision"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion_examen" ADD CONSTRAINT "FK_ad0d63f92a8393f0fd037896f58" FOREIGN KEY ("inscripcionId") REFERENCES "inscripcion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion_examen" ADD CONSTRAINT "FK_7831b25a3619a93f1a2d75ced67" FOREIGN KEY ("examenId") REFERENCES "examen_final"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "examen_final" ADD CONSTRAINT "FK_c3dfac3bbba8000899004bd3983" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "examen_final" ADD CONSTRAINT "FK_9c8964886f40f0598d05c7b9be1" FOREIGN KEY ("estudianteId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "correlativas_cursada" ADD CONSTRAINT "FK_b531012ccb0f933c750eb1ca984" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "correlativas_cursada" ADD CONSTRAINT "FK_13acc7d2fd20acd9ae7f9be4111" FOREIGN KEY ("correlativaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "correlativas_final" ADD CONSTRAINT "FK_fc0ea827459b7ab2b7198cd01c8" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "correlativas_final" ADD CONSTRAINT "FK_2abed773f9d0814ddbb74e55d2d" FOREIGN KEY ("correlativaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materia" ADD CONSTRAINT "FK_72990e606e0f93d655c41e89fc4" FOREIGN KEY ("departamentoId") REFERENCES "departamento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materia" ADD CONSTRAINT "FK_6fe2237e9ca17e0a1565ddd1c58" FOREIGN KEY ("jefeCatedraId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_48627f6fd1f0e55988a7e8d4fd3" FOREIGN KEY ("estudianteId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_c85979aba6a3d7c434348187474" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_e4fac3f4a37d93f56877d3aa102" FOREIGN KEY ("comisionId") REFERENCES "comision"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_7870399c012e8e086db97b9cf6c" FOREIGN KEY ("planEstudioId") REFERENCES "plan_estudio"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_cf46a20c344316c381c394f910a" FOREIGN KEY ("planEstudioId") REFERENCES "plan_estudio"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estado_academico" ADD CONSTRAINT "FK_a8d3bc6067c96cbbead759f04ee" FOREIGN KEY ("estudianteId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estado_academico" ADD CONSTRAINT "FK_6827a842372c2c0881fb9e54e08" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materia_planes_estudio" ADD CONSTRAINT "FK_c855ceccd6a1bafda47c5d986d0" FOREIGN KEY ("planEstudioId") REFERENCES "plan_estudio"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "materia_planes_estudio" ADD CONSTRAINT "FK_89119a766cc38d3b471c44f1c57" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materia_profesores" ADD CONSTRAINT "FK_d843d814b3b533333e65490d02d" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "materia_profesores" ADD CONSTRAINT "FK_6861a3382a55c8a497e59bfa027" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "materia_profesores" DROP CONSTRAINT "FK_6861a3382a55c8a497e59bfa027"`);
        await queryRunner.query(`ALTER TABLE "materia_profesores" DROP CONSTRAINT "FK_d843d814b3b533333e65490d02d"`);
        await queryRunner.query(`ALTER TABLE "materia_planes_estudio" DROP CONSTRAINT "FK_89119a766cc38d3b471c44f1c57"`);
        await queryRunner.query(`ALTER TABLE "materia_planes_estudio" DROP CONSTRAINT "FK_c855ceccd6a1bafda47c5d986d0"`);
        await queryRunner.query(`ALTER TABLE "estado_academico" DROP CONSTRAINT "FK_6827a842372c2c0881fb9e54e08"`);
        await queryRunner.query(`ALTER TABLE "estado_academico" DROP CONSTRAINT "FK_a8d3bc6067c96cbbead759f04ee"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_cf46a20c344316c381c394f910a"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_7870399c012e8e086db97b9cf6c"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_e4fac3f4a37d93f56877d3aa102"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_c85979aba6a3d7c434348187474"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_48627f6fd1f0e55988a7e8d4fd3"`);
        await queryRunner.query(`ALTER TABLE "materia" DROP CONSTRAINT "FK_6fe2237e9ca17e0a1565ddd1c58"`);
        await queryRunner.query(`ALTER TABLE "materia" DROP CONSTRAINT "FK_72990e606e0f93d655c41e89fc4"`);
        await queryRunner.query(`ALTER TABLE "correlativas_final" DROP CONSTRAINT "FK_2abed773f9d0814ddbb74e55d2d"`);
        await queryRunner.query(`ALTER TABLE "correlativas_final" DROP CONSTRAINT "FK_fc0ea827459b7ab2b7198cd01c8"`);
        await queryRunner.query(`ALTER TABLE "correlativas_cursada" DROP CONSTRAINT "FK_13acc7d2fd20acd9ae7f9be4111"`);
        await queryRunner.query(`ALTER TABLE "correlativas_cursada" DROP CONSTRAINT "FK_b531012ccb0f933c750eb1ca984"`);
        await queryRunner.query(`ALTER TABLE "examen_final" DROP CONSTRAINT "FK_9c8964886f40f0598d05c7b9be1"`);
        await queryRunner.query(`ALTER TABLE "examen_final" DROP CONSTRAINT "FK_c3dfac3bbba8000899004bd3983"`);
        await queryRunner.query(`ALTER TABLE "inscripcion_examen" DROP CONSTRAINT "FK_7831b25a3619a93f1a2d75ced67"`);
        await queryRunner.query(`ALTER TABLE "inscripcion_examen" DROP CONSTRAINT "FK_ad0d63f92a8393f0fd037896f58"`);
        await queryRunner.query(`ALTER TABLE "horario" DROP CONSTRAINT "FK_e15f4d22e3e790a903e5eef565a"`);
        await queryRunner.query(`ALTER TABLE "horario" DROP CONSTRAINT "FK_7c707c9c1f8b56b381e12162c2f"`);
        await queryRunner.query(`ALTER TABLE "horario" DROP CONSTRAINT "FK_2c31906f1be137431292d0766e9"`);
        await queryRunner.query(`ALTER TABLE "comision" DROP CONSTRAINT "FK_3eec2023337a05b05082e615e3c"`);
        await queryRunner.query(`ALTER TABLE "comision" DROP CONSTRAINT "FK_3b031ff32fb1f21b9eec28e20e2"`);
        await queryRunner.query(`ALTER TABLE "clase" DROP CONSTRAINT "FK_8cd6d132d0278db578b370e6bd7"`);
        await queryRunner.query(`ALTER TABLE "clase" DROP CONSTRAINT "FK_fb7f4acc691e9f579f39225fcfe"`);
        await queryRunner.query(`ALTER TABLE "clase" DROP CONSTRAINT "FK_df1e638ab6203b480e17ae6011d"`);
        await queryRunner.query(`ALTER TABLE "clase" DROP CONSTRAINT "FK_03880ab206e6c9173496407b186"`);
        await queryRunner.query(`ALTER TABLE "asistencia" DROP CONSTRAINT "FK_dc055a54b200f09315ee60a8e22"`);
        await queryRunner.query(`ALTER TABLE "asistencia" DROP CONSTRAINT "FK_197feedf6c94e57846e6b436a4e"`);
        await queryRunner.query(`ALTER TABLE "evaluaciones" DROP CONSTRAINT "FK_5819c9fc55bb56964c775d40d31"`);
        await queryRunner.query(`ALTER TABLE "evaluaciones" DROP CONSTRAINT "FK_26177eb590949744dfd2d625ac4"`);
        await queryRunner.query(`ALTER TABLE "evaluaciones" DROP CONSTRAINT "FK_1afd8efb246281fe06e9e1bc65b"`);
        await queryRunner.query(`ALTER TABLE "evaluaciones" DROP CONSTRAINT "FK_794c93fa7feaf1bdda025827c48"`);
        await queryRunner.query(`ALTER TABLE "plan_estudio" DROP CONSTRAINT "FK_18a90835b62888c63219633bca3"`);
        await queryRunner.query(`ALTER TABLE "departamento" DROP CONSTRAINT "FK_2fd9711a13a99100621e6122741"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6861a3382a55c8a497e59bfa02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d843d814b3b533333e65490d02"`);
        await queryRunner.query(`DROP TABLE "materia_profesores"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89119a766cc38d3b471c44f1c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c855ceccd6a1bafda47c5d986d"`);
        await queryRunner.query(`DROP TABLE "materia_planes_estudio"`);
        await queryRunner.query(`DROP TABLE "estado_academico"`);
        await queryRunner.query(`DROP TYPE "public"."estado_academico_estado_enum"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_rol_enum"`);
        await queryRunner.query(`DROP TABLE "inscripcion"`);
        await queryRunner.query(`DROP TABLE "materia"`);
        await queryRunner.query(`DROP TABLE "correlativas_final"`);
        await queryRunner.query(`DROP TABLE "correlativas_cursada"`);
        await queryRunner.query(`DROP TABLE "examen_final"`);
        await queryRunner.query(`DROP TABLE "inscripcion_examen"`);
        await queryRunner.query(`DROP TABLE "horario"`);
        await queryRunner.query(`DROP TYPE "public"."horario_dia_enum"`);
        await queryRunner.query(`DROP TABLE "comision"`);
        await queryRunner.query(`DROP TABLE "clase"`);
        await queryRunner.query(`DROP TYPE "public"."clase_estado_enum"`);
        await queryRunner.query(`DROP TABLE "asistencia"`);
        await queryRunner.query(`DROP TYPE "public"."asistencia_estado_enum"`);
        await queryRunner.query(`DROP TABLE "evaluaciones"`);
        await queryRunner.query(`DROP TYPE "public"."evaluaciones_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."evaluaciones_tipo_enum"`);
        await queryRunner.query(`DROP TABLE "plan_estudio"`);
        await queryRunner.query(`DROP TABLE "carrera"`);
        await queryRunner.query(`DROP TABLE "departamento"`);
    }

}
